/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.basvanderwilk.aslkids;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class raw {
        public static final int airplane=0x7f040000;
        public static final int apple=0x7f040001;
        public static final int baby=0x7f040002;
        public static final int ball=0x7f040003;
        public static final int bath=0x7f040004;
        public static final int battery=0x7f040005;
        public static final int bear=0x7f040006;
        public static final int bed=0x7f040007;
        public static final int bicycle=0x7f040008;
        public static final int bird=0x7f040009;
        public static final int black=0x7f04000a;
        public static final int boat=0x7f04000b;
        public static final int book=0x7f04000c;
        public static final int boy=0x7f04000d;
        public static final int bread=0x7f04000e;
        public static final int bus=0x7f04000f;
        public static final int butterfly=0x7f040010;
        public static final int candy=0x7f040011;
        public static final int car=0x7f040012;
        public static final int cat=0x7f040013;
        public static final int chair=0x7f040014;
        public static final int church=0x7f040015;
        public static final int cow=0x7f040016;
        public static final int crying=0x7f040017;
        public static final int deer=0x7f040018;
        public static final int dolphin=0x7f040019;
        public static final int donkey=0x7f04001a;
        public static final int drink=0x7f04001b;
        public static final int egg=0x7f04001c;
        public static final int elephant=0x7f04001d;
        public static final int fish=0x7f04001e;
        public static final int flower=0x7f04001f;
        public static final int food=0x7f040020;
        public static final int frenchfries=0x7f040021;
        public static final int hamburger=0x7f040022;
        public static final int horse=0x7f040023;
        public static final int hotdog=0x7f040024;
        public static final int house=0x7f040025;
        public static final int icecream=0x7f040026;
        public static final int kangaroo=0x7f040027;
        public static final int key=0x7f040028;
        public static final int lion=0x7f040029;
        public static final int mail=0x7f04002a;
        public static final int milk=0x7f04002b;
        public static final int monkey=0x7f04002c;
        public static final int moon=0x7f04002d;
        public static final int mouse=0x7f04002e;
        public static final int pancake=0x7f04002f;
        public static final int paper=0x7f040030;
        public static final int pen=0x7f040031;
        public static final int phone=0x7f040032;
        public static final int pig=0x7f040033;
        public static final int rainbow=0x7f040034;
        public static final int red=0x7f040035;
        public static final int school=0x7f040036;
        public static final int shoes=0x7f040037;
        public static final int sorry=0x7f040038;
        public static final int spider=0x7f040039;
        public static final int subway=0x7f04003a;
        public static final int sun=0x7f04003b;
        public static final int teacher=0x7f04003c;
        public static final int tiger=0x7f04003d;
        public static final int time=0x7f04003e;
        public static final int toilet=0x7f04003f;
        public static final int toothbrush=0x7f040040;
        public static final int train=0x7f040041;
        public static final int tree=0x7f040042;
        public static final int tree_1=0x7f040043;
        public static final int umbrella=0x7f040044;
        public static final int walk=0x7f040045;
        public static final int water=0x7f040046;
        public static final int white=0x7f040047;
        public static final int yellow=0x7f040048;
    }
    public static final class string {
        public static final int app_name=0x7f050001;
        public static final int billing_key_param=0x7f050000;
    }
    public static final class xml {
        public static final int config=0x7f030000;
    }
}
